seed: 123
num_workers: 2
device: "cuda"

train_path: /work/ga97/a97002/GRU_VAE/data_zinc/train.csv
valid_path: /work/ga97/a97002/GRU_VAE/data_zinc/test.csv
token_path: ../tokens/zinc_SFL_tokens.txt
SFL: true
bucketing: true
bucket_min: 20
bucket_max: 150
bucket_step: 10
batch_shuffle: true

embedding_dim: 128
enc_gru_layer: [256, 512, 1024]
latent_dim: 256
dec_gru_layer: [256, 512, 1024]

batch_size: 1024
steps: 50
dropout: 0.1
max_lr: 1.0e-1
warmup_step: 8000
patience_step: 10000
valid_step_range: 10
loss_log: true